FROM java:8-jdk-alpine 
COPY ./target/SpringRestWithDocker-0.0.1-SNAPSHOT.jar usr/app
WORKDIR usr/app
RUN sh -c "SpringRestWithDocker-0.0.1-SNAPSHOT.jar"
ENTRYPOINT ["java","-jar","SpringRestWithDocker-0.0.1-SNAPSHOT.jar"]